
[guild]
	#Enable or disable friendly fire for guild members.
	friendlyFire = false
	#Show guild names above players' heads
	showGuildNames = true
	#Item required to create a guild (e.g., 'minecraft:gold_ingot')
	guildCreationItem = "minecraft:gold_ingot"
	#Amount of item required to create a guild
	#Range: > 1
	guildCreationCost = 10
	#Enable or disable the guild buffs feature.
	enableGuildBuffs = true

