name: Send commits to Discord

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Post commit message to Discord
        run: |
          commits=$(jq -r '.commits[] | "- @\(.author.name) (<https://github.com/\(.author.username)>) ([#\(.id[0:7])](\(.url))): \(.message)"' $GITHUB_EVENT_PATH | tr '\n' '\n')
          if [ -n "$commits" ]; then
            payload=$(jq -n --arg content "$commits" '{content: $content}')
            curl -H "Content-Type: application/json" \
                 -X POST \
                 -d "$payload" \
                 ${{ secrets.DISCORD_WEBHOOK }}
          fi
